FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY . .
RUN go build -o orchestrator cmd/orchestrator/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder app/orchestrator .
EXPOSE 8080
CMD ["./orchestrator"]