FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod .
COPY . .
RUN go build -o agent cmd/agent/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder app/agent .
CMD ["./agent"]